apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-api
  namespace: stateless
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-api
  template:
    metadata:
      labels:
        app: web-api
    spec:
      containers:
        - name: web-api
          image: usaidrehan/bluelocalprd  # Updated image reference
         # image: usaidrehan/kashaflocal
          imagePullPolicy: Always
          ports:
            - containerPort: 54107
          env:
            - name: DB_HOST
              value: "postgres-service.stateful.svc.cluster.local"  # Updated service name for DB
            - name: DB_PORT
              value: "5432"
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: web-secret
                  key: DB_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: web-secret
                  key: DB_PASSWORD
            - name: DB_NAME
              value: "PSO_BI_Dev"
            - name: DB_CONNECTION_STRING
              value: "postgresql://$(DB_USER):$(DB_PASSWORD)@$(DB_HOST):$(DB_PORT)/$(DB_NAME)"  # Connection string
              
          # livenessProbe:
          #   httpGet:
          #     path: /api/AppSettings/GetRecentLogs
          #     port: 54107
          #   initialDelaySeconds: 15
          #   periodSeconds: 10
          # readinessProbe:
          #   httpGet:
          #     path: /api/AppSettings/GetRecentLogs
          #     port: 54107
          #   initialDelaySeconds: 5
          #   periodSeconds: 5 
---

apiVersion: v1
kind: Service
metadata:
  name: web-api-service
  namespace: stateless
spec:
  selector:
    app: web-api
  ports:
    - protocol: TCP
      port: 54107      # Internal Cluster Port
      targetPort: 54107 # Container Port
      nodePort: 32070   # Exposed Port (Should be within 30000–32767)
  type: NodePort
  externalTrafficPolicy: Local  # Ensures direct routing to the node


# apiVersion: v1
# kind: Service
# metadata:
#   name: web-api-service
#   namespace: stateless
# spec:
#   selector:
#     app: web-api
#   ports:
#     - protocol: TCP
#       port: 54107 #9080
#       targetPort: 54107
#       nodePort: 32070  # Chosen within valid range (30000–32767)
#   type: NodePort


# apiVersion: v1
# kind: Service
# metadata:
#   name: web-api-service
#   namespace: stateless
# spec:
#   selector:
#     app: web-api
#   ports:
#     - protocol: TCP
#       port: 9080
#       targetPort: 54107
#   type: ClusterIP  # Use LoadBalancer for external access
