apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: stateful
data:
  postgres.conf: |
    wal_level = replica
    max_wal_senders = 10
    wal_keep_size = 64
    hot_standby = on
  pg_hba.conf: |
    host all all all md5
