apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-pv
  labels:
    type: local
spec:
  storageClassName: local-storage  # Custom storage class
  capacity:
    storage: 2Gi  # 2GB Storage
  accessModes:
    - ReadWriteOnce  # Only one node can mount it at a time
  volumeMode: Filesystem  # Default mode
  persistentVolumeReclaimPolicy: Retain  # Prevents auto-deletion on PVC deletion
  local:
    path: /mnt/data/blue_db  # Host path for storage
