apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-pv
  labels:
    app: postgres-db
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  hostPath:
    path: /mnt/data/blue_db
    type: DirectoryOrCreate
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem