apiVersion: v1
kind: PersistentVolume
metadata:
  name: db-pv
  labels:
    app: postgres-db
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage
  hostPath:
    path: /mnt/data/blue_db
    type: DirectoryOrCreate
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem


# # apiVersion: v1
# # kind: PersistentVolume
# # metadata:
# #   name: db-pv
# #   labels:
# #     app: postgres-db
# # spec:
# #   capacity:
# #     storage: 2Gi
# #   accessModes:
# #     - ReadWriteOnce
# #   storageClassName: local-storage
# #   hostPath:
# #     path: /mnt/data/blue_db
# #     type: DirectoryOrCreate
# #   persistentVolumeReclaimPolicy: Retain
# #   volumeMode: Filesystem

# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: db-pv
#   labels:
#     app: postgres-db
# spec:
#   capacity:
#     storage: 2Gi
#   accessModes:
#     - ReadWriteOnce
#   storageClassName: local-storage
#   hostPath:
#     path: /mnt/data/blue_db
#     type: DirectoryOrCreate
#   persistentVolumeReclaimPolicy: Retain
#   volumeMode: Filesystem
#   nodeAffinity:
#     required:
#       nodeSelectorTerms:
#       - matchExpressions:
#         - key: kubernetes.io/hostname
#           operator: In
#           values:
#           - ubuntuqbs  # Replace with your actual node name