apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-pvc
  namespace: stateful  # Should match the DB namespace
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 2Gi  # Requesting 2GB storage
  storageClassName: localstorage  # Must match PV's storage class
